export const menu=[
       {
              name:"Home",
              items:[
                     {
                       item1:"item",
                       path:"/item"
                     },
                     {
                       item1:"item1",
                       path:"/item"
                     },
                     {
                       item1:"item2",
                       path:"/item"
                     },
                     {
                       item1:"item3",
                       path:"/item"
                     },
              ]
       },
       {
              name:"About",
              items:[
                     {
                       item1:"item",
                       path:"/item"
                     },
                     {
                       item1:"item1",
                       path:"/item"
                     },
                     {
                       item1:"item2",
                       path:"/item"
                     },
                     {
                       item1:"item3",
                       path:"/item"
                     },
              ]
       },
       {
              name:"Services",
              items:[
                     {
                       item1:"item",
                       path:"/item"
                     },
                     {
                       item1:"item1",
                       path:"/item"
                     },
                     {
                       item1:"item2",
                       path:"/item"
                     },
                     {
                       item1:"item3",
                       path:"/item"
                     },
              ]
       },
       {
              name:"Chats",
              items:[
                     {
                       item1:"item",
                       path:"/item"
                     },
                     {
                       item1:"item1",
                       path:"/item"
                     },
                     {
                       item1:"item2",
                       path:"/item"
                     },
                     {
                       item1:"item3",
                       path:"/item"
                     },
              ]
       },
       {
              name:"Contacts",
              items:[
                     {
                       item1:"item",
                       path:"/item"
                     },
                     {
                       item1:"item1",
                       path:"/item"
                     },
                     {
                       item1:"item2",
                       path:"/item"
                     },
                     {
                       item1:"item3",
                       path:"/item"
                     },
              ]
       }
]


export const images=[
 "https://images.unsplash.com/photo-1575936123452-b67c3203c357?fm=jpg&q=60&w=3000&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8aW1hZ2V8ZW58MHx8MHx8fDA%3D",
 
 "https://images.pexels.com/photos/1054655/pexels-photo-1054655.jpeg?cs=srgb&dl=pexels-hsapir-1054655.jpg&fm=jpg",

 "https://images.pexels.com/photos/326055/pexels-photo-326055.jpeg?cs=srgb&dl=pexels-pixabay-326055.jpg&fm=jpg",
 "https://images.unsplash.com/photo-1526779259212-939e64788e3c?fm=jpg&q=60&w=3000&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NHx8ZnJlZSUyMGltYWdlc3xlbnwwfHwwfHx8MA%3D%3D",
 "https://cdn.pixabay.com/photo/2024/05/26/10/15/bird-8788491_1280.jpg"
]